apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  creationTimestamp: "2026-08-18T07:01:56Z"
  name: web-app
  namespace: production
  resourceVersion: "173385"
  uid: 6dd386a4-a35c-4b78-a89c-e4cf195c6d5a
spec:
  maxReplicas: 10
  metrics:
  - resource:
      name: cpu
      target:
        averageUtilization: 50
        type: Utilization
    type: Resource
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: web-app
status:
  conditions:
  - lastTransitionTime: "2026-08-18T07:02:11Z"
    message: recent recommendations were higher than current one, applying the highest
      recent recommendation
    reason: ScaleDownStabilized
    status: "True"
    type: AbleToScale
  - lastTransitionTime: "2026-08-18T07:02:11Z"
    message: the HPA was able to successfully calculate a replica count from cpu resource
      utilization (percentage of request)
    reason: ValidMetricFound
    status: "True"
    type: ScalingActive
  - lastTransitionTime: "2026-08-18T08:14:14Z"
    message: the desired count is within the acceptable range
    reason: DesiredWithinRange
    status: "False"
    type: ScalingLimited
  currentMetrics:
  - resource:
      current:
        averageUtilization: 10
        averageValue: 10m
      name: cpu
    type: Resource
  currentReplicas: 8
  desiredReplicas: 8
  lastScaleTime: "2026-08-18T08:14:59Z"
